pipeline:
  python_app:
    image: python:3.5.1-alpine
    environment:
      APP_SETTINGS: 'project.config.DroneCiConfig'
      SECRET_KEY: 'really secret'
      CSRF_SECRET: 'really secret'
      DATABASE_URL: 'postgres://postgres@database/travis_ci_test'
      SELENIUM_REMOTE: 'http://selenium:4444/wd/hub'
      REDIS_URL: 'redis://redis:6379'
      
    commands:
      - apk update
      - apk add git postgresql-dev build-base
      - pip install --upgrade pip
      - pip3 install -r requirements.txt
      - pip3 install -r requirements-test.txt
      - pip3 install flake8
      - python3 manage.py db upgrade
      - gunicorn project:whitenoise_app &
      - flake8 project/
      - mypy --fast-parser --strict-optional --silent-imports project/
      - python3 -m unittest project.tests.functional
  frontend:
    image: node
    commands:
      - npm install
      - npm run lint

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=travis_ci_test
  selenium:
    image: selenium/standalone-chrome
  redis:
    image: redis:3.0
