language: node_js
python:
  - "3.5"
node_js:
  - "5.8"

services:
  - redis-server
  - postgresql

env:
  - APP_SETTINGS=project.config.VaggaTestingConfig
  - SECRET_KEY=really secret
  - CSRF_SECRET=really secret
  - DATABASE_URL=postgres://localhost/travis_ci_test

addons:
  artifacts: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-test.txt
  - pip3 install flake8
  - npm install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python3 manage.py db upgrade
  - python3 run.py &

script:
  - flake8 project/
  - npm run lint
  - python3 -m unittest project.tests.functional
