sudo: required
dist: trusty
language: node_js
python:
  - "3.5"
node_js:
  - "5.8"

services:
  - redis-server
  - postgresql

env:
  - APP_SETTINGS="project.config.VaggaTestingConfig"
  - SECRET_KEY="really secret"
  - CSRF_SECRET="really secret"
  - DATABASE_URL="postgres://localhost/travis_ci_test"

addons:
  artifacts: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # nodejs >v4 compiler requirements
      - g++-4.8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python3-dev
  - python3 -V
  - pip3 -V

install:
  - pip3 install -r requirements.txt --user `whoami`
  - pip3 install -r requirements-test.txt --user `whoami`
  - pip3 install flake8 --user `whoami`
  - npm install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python3 manage.py db upgrade
  - python3 run.py &

script:
  - flake8 project/
  - npm run lint
  - python3 -m unittest project.tests.functional
