"""empty message

Revision ID: 1f49fb7041be
Revises: be09cc5ecd0b
Create Date: 2016-08-01 19:22:33.956816

"""

# revision identifiers, used by Alembic.
revision = '1f49fb7041be'
down_revision = 'be09cc5ecd0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase', sa.Column('language', sa.Unicode(), nullable=False, server_default='dummy'))
    op.execute("""
        UPDATE phrase
        SET language = source_language;
    """)
    op.alter_column('phrase', 'language', server_default=None)
    op.drop_column('phrase', 'translated_language')
    op.drop_column('phrase', 'source_language')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase', sa.Column('source_language', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('phrase', sa.Column('translated_language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('phrase', 'language')
    ### end Alembic commands ###
