"""empty message

Revision ID: 2fb060ee52e7
Revises: b32949e5c95f
Create Date: 2016-04-09 15:14:13.104456

"""

# revision identifiers, used by Alembic.
revision = '2fb060ee52e7'
down_revision = 'b32949e5c95f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.Unicode(), nullable=True))
    op.add_column('user', sa.Column('register_type', sa.Integer(), nullable=False, server_default="1"))
    op.alter_column('user', 'auth_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'register_type')
    op.drop_column('user', 'password')
    ### end Alembic commands ###
