"""empty message

Revision ID: b32949e5c95f
Revises: 09a2461dda83
Create Date: 2016-03-13 14:29:39.973660

"""

# revision identifiers, used by Alembic.
revision = 'b32949e5c95f'
down_revision = '09a2461dda83'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('word', 'phrase')
    op.alter_column('phrase', 'date_is_available_after', new_column_name='date_available')

    op.alter_column('phrase', 'language', new_column_name='source_language')
    op.alter_column('phrase', 'text', new_column_name='source_text')

    op.add_column(
        'phrase',
        sa.Column('translated_language', sa.Unicode(), nullable=True)
    )
    op.add_column(
        'phrase',
        sa.Column('translated_text', sa.Unicode(), nullable=True)
    )

    op.execute("""
        UPDATE phrase
        SET translated_language = translated.source_language, translated_text = translated.source_text
        FROM (
          SELECT translation.word_id source_id, translated_phrase.source_language, translated_phrase.source_text
          FROM phrase translated_phrase
          JOIN translation ON translation.translated_id = translated_phrase.id
        ) translated
        WHERE translated.source_id = phrase.id;

        UPDATE phrase
        SET status = 1
        FROM translation
        WHERE tranlation.translated_id = phrase.id;
    """)
    op.drop_table('translation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    raise Exception('Do not downgrade!')
    ### end Alembic commands ###
