"""empty message

Revision ID: be09cc5ecd0b
Revises: 2fb060ee52e7
Create Date: 2016-07-24 17:37:03.632012

"""

# revision identifiers, used by Alembic.
revision = 'be09cc5ecd0b'
down_revision = '2fb060ee52e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
